### ISSUE TITLE
Integration tests fail @NotNull constraints

### ISSUE THREAD

**Issue by tmjee** [jcabi/jcabi-dynamo#60]
When fixing #56,  the following integration tests failed. It should be mostly due to mock data attributes being null. added @todo and @Ignore to those tests

- AwsIteratorITCase
- RegionITCase

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@tmjee I didn't understand what is the problem. How can I reproduce it?

**Comment by tmjee** [comment]
@yegor256  I ran the following 
```
 $> mvn clean install -Pqulice
```
and some those integration tests failed when aspectj kicks in checking not null on annotated parameters.

**Comment by yegor256** [comment]
@tmjee but travis build is clean... and I just ran it locally - it's clean.

**Comment by tmjee** [comment]
@yegor256 I'm getting the following failures. Having said that it might be just my configurations. More than happy to close this.
```
[ERROR] pool-2-thread-6 com.jcabi.dynamo.AwsTable: #print(NULL): thrown javax.validation.ConstraintViolationException(attribute capacity cannot be null) out of com.jcabi.aspects.aj.MethodValidator#validate[181] in 825µs
[ERROR] pool-2-thread-6 com.jcabi.dynamo.AwsTable: #put('hash-key={S: i0,}; range-key={N: 1,}'): thrown javax.validation.ConstraintViolationException(attribute capacity cannot be null) out of com.jcabi.aspects.aj.MethodValidator#validate[181] in 56ms
[WARN] pool-2-thread-6 com.jcabi.dynamo.retry.ReTable: #put(): attempt #3/3 failed with javax.validation.ConstraintViolationException in 58ms (30s in total): attribute capacity cannot be null
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 54.996 sec <<< FAILURE! - in com.jcabi.dynamo.AwsIteratorITCase
iteratesItems(com.jcabi.dynamo.AwsIteratorITCase)  Time elapsed: 22.416 sec  <<< ERROR!
javax.validation.ConstraintViolationException: attribute capacity cannot be null
	at com.jcabi.aspects.aj.MethodValidator.validate(MethodValidator.java:181)
	at com.jcabi.aspects.aj.MethodValidator.beforeMethod(MethodValidator.java:95)
	at com.jcabi.dynamo.AwsTable.print_aroundBody12(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable$AjcClosure13.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.print(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable.put_aroundBody0(AwsTable.java:117)
	at com.jcabi.dynamo.AwsTable$AjcClosure1.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.put(AwsTable.java:108)
	at com.jcabi.dynamo.retry.ReTable.put_aroundBody0(ReTable.java:81)
	at com.jcabi.dynamo.retry.ReTable$AjcClosure1.run(ReTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
	at com.jcabi.dynamo.retry.ReTable.put(ReTable.java:81)
	at com.jcabi.dynamo.AwsIteratorITCase.iteratesItems(AwsIteratorITCase.java:59)

iteratesItemsAndDeletes(com.jcabi.dynamo.AwsIteratorITCase)  Time elapsed: 32.58 sec  <<< ERROR!
javax.validation.ConstraintViolationException: attribute capacity cannot be null
	at com.jcabi.aspects.aj.MethodValidator.validate(MethodValidator.java:181)
	at com.jcabi.aspects.aj.MethodValidator.beforeMethod(MethodValidator.java:95)
	at com.jcabi.dynamo.AwsTable.print_aroundBody12(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable$AjcClosure13.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.print(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable.put_aroundBody0(AwsTable.java:117)
	at com.jcabi.dynamo.AwsTable$AjcClosure1.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.put(AwsTable.java:108)
	at com.jcabi.dynamo.retry.ReTable.put_aroundBody0(ReTable.java:81)
	at com.jcabi.dynamo.retry.ReTable$AjcClosure1.run(ReTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
	at com.jcabi.dynamo.retry.ReTable.put(ReTable.java:81)
	at com.jcabi.dynamo.AwsIteratorITCase.iteratesItemsAndDeletes(AwsIteratorITCase.java:80)
```

and this

```
[ERROR] pool-2-thread-5 com.jcabi.dynamo.AwsTable: #print(NULL): thrown javax.validation.ConstraintViolationException(attribute capacity cannot be null) out of com.jcabi.aspects.aj.MethodValidator#validate[181] in 478µs
[ERROR] pool-2-thread-5 com.jcabi.dynamo.AwsTable: #put('BhNEwoNi={S: 075eZy6mow,}; hash-key={S: tguxQMbn0n,}; range-key={N: 0,}'): thrown javax.validation.ConstraintViolationException(attribute capacity cannot be null) out of com.jcabi.aspects.aj.MethodValidator#validate[181] in 56ms
[WARN] pool-2-thread-5 com.jcabi.dynamo.retry.ReTable: #put(): attempt #3/3 failed with javax.validation.ConstraintViolationException in 57ms (10s in total): attribute capacity cannot be null
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 49.974 sec <<< FAILURE! - in com.jcabi.dynamo.RegionITCase
retrievesAttributesFromDynamo(com.jcabi.dynamo.RegionITCase)  Time elapsed: 37.472 sec  <<< ERROR!
javax.validation.ConstraintViolationException: attribute capacity cannot be null
	at com.jcabi.aspects.aj.MethodValidator.validate(MethodValidator.java:181)
	at com.jcabi.aspects.aj.MethodValidator.beforeMethod(MethodValidator.java:95)
	at com.jcabi.dynamo.AwsTable.print_aroundBody12(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable$AjcClosure13.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.print(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable.put_aroundBody0(AwsTable.java:117)
	at com.jcabi.dynamo.AwsTable$AjcClosure1.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.put(AwsTable.java:108)
	at com.jcabi.dynamo.retry.ReTable.put_aroundBody0(ReTable.java:81)
	at com.jcabi.dynamo.retry.ReTable$AjcClosure1.run(ReTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
	at com.jcabi.dynamo.retry.ReTable.put(ReTable.java:81)
	at com.jcabi.dynamo.RegionITCase.retrievesAttributesFromDynamo(RegionITCase.java:126)

worksWithAmazon(com.jcabi.dynamo.RegionITCase)  Time elapsed: 12.502 sec  <<< ERROR!
javax.validation.ConstraintViolationException: attribute capacity cannot be null
	at com.jcabi.aspects.aj.MethodValidator.validate(MethodValidator.java:181)
	at com.jcabi.aspects.aj.MethodValidator.beforeMethod(MethodValidator.java:95)
	at com.jcabi.dynamo.AwsTable.print_aroundBody12(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable$AjcClosure13.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.print(AwsTable.java:196)
	at com.jcabi.dynamo.AwsTable.put_aroundBody0(AwsTable.java:117)
	at com.jcabi.dynamo.AwsTable$AjcClosure1.run(AwsTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsTable.put(AwsTable.java:108)
	at com.jcabi.dynamo.retry.ReTable.put_aroundBody0(ReTable.java:81)
	at com.jcabi.dynamo.retry.ReTable$AjcClosure1.run(ReTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
	at com.jcabi.dynamo.retry.ReTable.put(ReTable.java:81)
	at com.jcabi.dynamo.RegionITCase.worksWithAmazon(RegionITCase.java:67)
```

Tests in error: 
  AwsIteratorITCase.iteratesItems:59 » ConstraintViolation attribute capacity ca...
  AwsIteratorITCase.iteratesItemsAndDeletes:80 » ConstraintViolation attribute c...
  RegionITCase.retrievesAttributesFromDynamo:126 » ConstraintViolation attribute...
  RegionITCase.worksWithAmazon:67 » ConstraintViolation attribute capacity canno...

**Comment by tmjee** [comment]
Closing issue. Cannot be reproduce.
