### ISSUE TITLE
Problem running AwsIteratorITCase.java test

### ISSUE THREAD

**Issue by olegsimanov** [jcabi/jcabi-dynamo#67]
Hi, 
I forked, cloned and ran all mvn tests in the project.  As result there were no failing tests. 
After I commented out @Ignore annotation for iteratesItems() and iteratesItemsAndDeletes() in  <code>src/test/java/com/jcabi/dynamo/AwsIteratorITCase.java</code> 
and run: <code>mvn test -Dtest=com.jcabi.dynamo.AwsIteratorITCase</code>
they failed with a NumberFormatException wrapped into ExceptionInInitializerError: 
```
ava.lang.ExceptionInInitializerError
	at com.jcabi.dynamo.AwsIteratorITCase.iteratesItems(AwsIteratorITCase.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:454)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.jcabi.dynamo.RegionMock.<clinit>(RegionMock.java:63)
	... 19 more
```

It looks like <code>failsafe.port</code> environment variable is missing. Where can I find this variable? Or may be I'm doing something wrong?

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@olegsimanov these tests must be run by maven-failsafe-plugin, not by maven-surefire-plugin, like you're doing now. Always run `mvn clean install`, if you're not sure.

**Comment by olegsimanov** [comment]
Thank you for the answer
